[package]
name = "super_rogue_soccer"
version = "0.1.0"
edition = "2024"

[features]
debug = ["dep:bevy-inspector-egui"]

[dependencies]
bevy = "0.15.3"
bevy-inspector-egui = { version = "0.29.1", optional = true }
