pub const FIRST_NAMES: &[&str] = &[
    "NERT", "KENN", "FERGIT", "COLE", "LOOD", "TAENIS", "MARNEL", "DONY", "GIN", "WOB", "TANNY",
    "HUDGYN", "FRAVEN", "RARR", "DORSE", "ROY", "TENPE", "VARLIN", "POTT", "AM", "SNARRY", "BOBS",
    "RENLY", "CEYNEI", "HOM", "ODOOD", "GARY", "JARIS", "ERL", "LENN", "DAN", "YANS", "MOB",
    "BANNOE", "AL", "JINNEIL",
];
pub const FIRST_NAMES_2: &[&str] = &[
    "SLEVE",
    "ONSON",
    "DARRYL",
    "ANATOLI",
    "REY",
    "GLENALLEN",
    "MARIO",
    "RAUL",
    "KEVIN",
    "TONY",
    "BOBSON",
    "WILLIE",
    "JEROMY",
    "SCOTT",
    "SHOWN",
    "DEAN",
    "MIKE",
    "DWIGT",
    "TIM",
    "KARL",
    "MIKE",
    "TODD",
];

pub const LAST_NAMES: &[&str] = &[
    "BISELS",
    "NITVARN",
    "HOTE",
    "BITZRON",
    "JANGLOSTI",
    "TELLRON",
    "HARY",
    "OLERBERZ",
    "GINLONS",
    "WONKOZ",
    "MLITNIRT",
    "SASDARL",
    "POOTH",
    "DICK",
    "HINTLINE",
    "GAMO",
    "LAOB",
    "GENMIST",
    "KORHIL",
    "O'ERSON",
    "SHITWON",
    "PEARE",
    "MLYNREN",
    "DOOBER",
    "WAPKO",
    "JORGEUDEY",
    "BANPS",
    "FORTA",
    "JIVLIIZ",
    "WOBSES",
    "BOYO",
    "LOOVENSAN",
    "WELRONZ",
    "RODYLAR",
    "SWERMIRSTZ",
    "ROBENKO",
];

pub const LAST_NAMES_2: &[&str] = &[
    "MCDICHAEL",
    "SWEEMEY",
    "ARCHIDELD",
    "SMORIN",
    "McSRIFF",
    "MIXON",
    "McRLWAIN",
    "NOGILNY",
    "SMEHRIK",
    "DUGNUTT",
    "DUSTICE",
    "GRIDE",
    "DOURQUE",
    "FURCOTTE",
    "WESREY",
    "TRUK",
    "RORTUGAL",
    "SANDAELE",
    "DANDLETON",
    "SERNANDEZ",
    "BONZALES",
];
